# Generated by Django 4.2.16 on 2024-10-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_groups_user_is_superuser_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="operating_license",
            field=models.TextField(blank=True, null=True),
        ),
    ]
