# Generated by Django 4.2.16 on 2024-10-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_charityorganization"),
    ]

    operations = [
        migrations.AddField(
            model_name="charityorganization",
            name="operating_license",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="operating_license",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
