# Generated by Django 4.2.16 on 2024-10-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_charityorganization_operating_license_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="operating_license",
        ),
    ]
