# Generated by Django 4.2.16 on 2024-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_operating_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("donor", "Người quyên góp"),
                    ("charity", "Tổ chức từ thiện"),
                    ("recipient", "Người nhận hỗ trợ"),
                ],
                default="donor",
                max_length=20,
            ),
        ),
    ]
