# Generated by Django 4.2.16 on 2024-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("donor", "Người quyên góp"),
                    ("charity", "Tổ chức từ thiện"),
                    ("recipient", "Người nhận hỗ trợ"),
                    ("admin", "System Administrator"),
                ],
                default="donor",
                max_length=20,
            ),
        ),
    ]
