# Generated by Django 4.2.16 on 2024-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="disaster_area",
        ),
        migrations.AddField(
            model_name="campaign",
            name="disaster_areas",
            field=models.ManyToManyField(to="donations.disasterarea"),
        ),
    ]
