# Generated by Django 4.2.16 on 2024-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_remove_campaign_disaster_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="campaign_thumbnails/"
            ),
        ),
    ]
