# Generated by Django 4.2.16 on 2024-12-15 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donations", "0005_alter_donation_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "Đang tiến hành"), ("completed", "Đã hoàn thành")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="disasterarea",
            name="severity",
            field=models.CharField(
                choices=[("low", "Thấp"), ("moderate", "Vừa"), ("high", "Cao")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Chuyển khoản ngân hàng"),
                    ("e_wallet", "Ví điện tử"),
                    ("credit_card", "Thẻ tín dụng"),
                    ("cash", "Tiền mặt"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="donations.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
